# Generated by Django 3.2.13 on 2023-05-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('adult', models.BooleanField()),
                ('backdrop_path', models.TextField(null=True)),
                ('genre_ids', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('original_language', models.CharField(max_length=10)),
                ('original_title', models.TextField()),
                ('overview', models.TextField()),
                ('popularity', models.TextField()),
                ('poster_path', models.TextField(null=True)),
                ('release_date', models.DateField()),
                ('title', models.TextField()),
                ('video', models.BooleanField()),
                ('vote_average', models.TextField()),
                ('vote_count', models.IntegerField()),
            ],
        ),
    ]
