# Generated by Django 3.2.12 on 2023-05-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.BooleanField(null=True)),
                ('backdrop_path', models.TextField(null=True)),
                ('original_language', models.CharField(max_length=10, null=True)),
                ('original_title', models.TextField(null=True)),
                ('overview', models.TextField(null=True)),
                ('popularity', models.FloatField(null=True)),
                ('poster_path', models.TextField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('title', models.TextField(null=True)),
                ('video', models.BooleanField(null=True)),
                ('vote_average', models.FloatField(null=True)),
                ('vote_count', models.IntegerField(null=True)),
                ('genre', models.ManyToManyField(related_name='genre_movie', to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.BooleanField()),
                ('gender', models.IntegerField()),
                ('department', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('popularity', models.FloatField()),
                ('profile_path', models.TextField(null=True)),
                ('known', models.ManyToManyField(related_name='actor_movie', to='movies.Movie')),
            ],
        ),
    ]
