# Generated by Django 3.2.13 on 2023-05-17 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20230517_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre_id',
        ),
    ]
