# Generated by Django 3.2.13 on 2023-05-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_comment_recomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre_users',
        ),
    ]
