# Generated by Django 3.2.13 on 2023-05-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_comment_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='vote',
        ),
    ]
