# Generated by Django 3.2.13 on 2023-05-25 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_comment_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomments', to='movies.comment'),
        ),
    ]
