# Generated by Django 3.2.13 on 2023-05-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default='default.jpg', upload_to='user_images/'),
        ),
    ]
