# Generated by Django 3.2.13 on 2023-05-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_genre_genre_users'),
        ('accounts', '0004_alter_user_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_genres',
            field=models.ManyToManyField(related_name='genre_users', to='movies.Genre'),
        ),
    ]
