# Generated by Django 3.2.13 on 2023-05-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_like_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='One_liner',
            field=models.CharField(default='안녕하세요!', max_length=100),
        ),
    ]
