# Generated by Django 3.2.13 on 2023-05-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230519_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='like_user',
            new_name='like_users',
        ),
        migrations.AlterField(
            model_name='review',
            name='watch_date',
            field=models.DateField(),
        ),
    ]
