# Generated by Django 3.2.13 on 2023-05-24 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230523_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='vote',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
